USE sucos;
ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tbcliente (
CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADADE,ESTADO,CEP,IDADE,SEXO,
LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA,DATA_NASCIMENTO)
VALUE('01234567890','Gabriel dos Santos Soares','Rua Projetada A número 10','','Vila Romana','Gardênia','Rio de Janeiro','22765430',25,'M',10000.00,2000,0,'1997-04-10' );

SELECT * FROM tbcliente;